version: build_number_{build}
configuration: Release
skip_tags: true
init:
- ps: "$v = [regex]::match($env:APPVEYOR_REPO_BRANCH,'release/(.*)').Groups[1].Value\nWrite-Host \"On branch $($env:APPVEYOR_REPO_BRANCH)\"\nIF($v) { \n   $env:VERSION_FROM_BRANCH = \"$($v).$($env:APPVEYOR_BUILD_NUMBER)\"\n} else {\n   $env:VERSION_FROM_BRANCH = \"0.0.0.$($env:APPVEYOR_BUILD_NUMBER)\"\n}\nWrite-Host \"Set version to $($env:VERSION_FROM_BRANCH)\""
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(VERSION_FROM_BRANCH)
  assembly_file_version: $(VERSION_FROM_BRANCH)
  assembly_informational_version: $(VERSION_FROM_BRANCH)
before_build:- ps: >-    mkdir tools    NuGet.exe restore TimberWinR.sln
build:
  verbosity: minimal
after_build:
- ps: >-
    cat chocolateyInstall.ps1.template|%{$_-replace "\$\{version\}",$env:VERSION_FROM_BRANCH} > tools\chocolateyInstall.ps1
    cat chocolateyUninstall.ps1.template|%{$_-replace "\$\{version\}",$env:VERSION_FROM_BRANCH} > tools\chocolateyUninstall.ps1
    cat tools\chocolateyUninstall.ps1
    cat timberwinr.nuspec.template|%{$_-replace "\$\{version\}",$env:VERSION_FROM_BRANCH} > timberwinr.nuspec
    choco pack timberwinr.nuspec
artifacts:
- path: .\*.nupkg
  name: NuGet
- path: TimberWinR.ServiceHost\bin\*\*.dll
  name: Dlls
- path: TimberWinR.ServiceHost\bin\*\*.exe
  name: Exes
- path: TimberWix\bin\*\*.msi
  name: MSI 
deploy:
- provider: NuGet
  api_key:
    secure: y8zhZTNm3PWLLxtKiMO79Shx3TyG3lnuGpJ6J7GT+2SihEspFxuBXz+WvmI6qzX+
  skip_symbols: true
  artifact: NuGet
  on:
    branch: /release/.*/
- provider: GitHub
  release: $(VERSION_FROM_BRANCH)
  auth_token:
    secure: bk7/M9w924viJpK+R84lnLWYeL/NLCZsdei9cbgXtN7Gzy3OVdNSeM36XA173/v9
  artifact: Dlls, Exes, MSI
  on:
    branch: /release/.*/